### ISSUE TITLE
Error creating new website

### ISSUE THREAD

**Issue by electron64** [gma/nesta#171]
Hello i have an error when i try to create a new nesta website.
`nesta new mysite.com
/usr/lib/ruby/2.3.0/rubygems/specification.rb:2287:in `raise_if_conflicts': Unable to activate nesta-0.11.1, because tilt-2.0.7 conflicts with tilt (~> 1.4) (Gem::ConflictError)
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/nesta-0.11.1/lib/nesta.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/nesta-0.11.1/lib/nesta/app.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/nesta-0.11.1/lib/nesta/commands.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/nesta-0.11.1/bin/nesta:5:in `<top (required)>'
	from /usr/local/bin/nesta:22:in `load'
	from /usr/local/bin/nesta:22:in `<main>'`

**Comment by electron64** [comment]
Solved.
